### ISSUE TITLE
User can search for anime

### ISSUE THREAD

**Issue by JeffreyMejia** [JeffreyMejia/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for anime by name get back multiple results for the show or any related movies or OVAs along with other similarly titled anime.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display results for anime that was searched for or anything similarly titled. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-06 092739](https://github.com/JeffreyMejia/front-end-project/assets/154576898/695e02af-ea33-4fd1-9da7-c0071bcd97f6)
![Screenshot 2024-03-06 092751](https://github.com/JeffreyMejia/front-end-project/assets/154576898/6d8113bb-28df-4cd1-b595-f0c48aa21d23)
![Screenshot 2024-03-06 092807](https://github.com/JeffreyMejia/front-end-project/assets/154576898/07c6777e-faaf-48b3-a01b-171f68272dea)
![Screenshot 2024-03-06 092828](https://github.com/JeffreyMejia/front-end-project/assets/154576898/1cc13c1c-ed65-416c-843c-65731a0e9cda)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write HTML and CSS for landing page with mobile in mind first.
   - [x] Create layouts with the correct media queries to make a responsive page.
   - [x] Make sure the page is responsive for desktop and looks like the created wireframes. 
- [x] Add unordered list to html below landing page. This will be the representation for the data model created from the search.
- [x]  Create dummy entries to make sure the page will looks like the wire frames.
   - [x] Make sure it is responsive to in both mobile and desktop. 
   - [x] Make sure it is hidden until the user searches for something on the landing page. 
- [x] define a function called `renderSearch`. This function will return objects created with the API fetch. It should generate a DOM tree that will represent a single object from the array objects..
- [x] Add event listener to to search input that listens for `keydown` event. In the callback function data will fetched from the Jinkan API.
   - [x] create a conditional statement that uses that interpolates the the input value of the search into the fetch if the key matches `Enter`.
   - [x] Loop through the array calling `renderSearch` function to generate DOM tree for the search. 
   - [x] append the search to the unordered list element in the html.
- [x] Define function called `viewSwap` with one parameter called `view`. The function should show the view of the provided argument.
   - [x]  Update callback function for the input event listener to call the `viewSwap` function. This way the view will change to the search results when the user searches for an anime.
- [x] In the html add another text input to the nav bar for users to search when they're not on the landing page.
   - [x] Make sure the html matches the wireframes and is responsive. 
- [x] add Font Awesome magnifying glass icon next to input
- [x] make sure that the magnifying glass icon and the nav bar search are hidden when on the landing page by updating the `viewSwap` function
- [x] Add another event listener to the new search input listening for `keydown` events.
   - [x] Make sure the callback function uses similar code to the other search input.
   - [x] before looping through `anime.data` array, loop through the `ul` element and remove previous `li` elements so the previous search does not show.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
