### ISSUE TITLE
User can view individual anime details 

### ISSUE THREAD

**Issue by JeffreyMejia** [JeffreyMejia/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When the "More details" section of the displayed search is clicked the user will be taken to a new display that features more information about the anime.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display a more detailed description of the anime that includes details like synopsis, rating, time aired etc.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2024-03-06 092807](https://github.com/JeffreyMejia/front-end-project/assets/154576898/ed0428a1-dc02-4396-8759-7df30d1ea62c)
![Screenshot 2024-03-06 094616](https://github.com/JeffreyMejia/front-end-project/assets/154576898/4f597b23-d7fb-47c7-a550-9b7891df61ed)
![Screenshot 2024-03-06 094629](https://github.com/JeffreyMejia/front-end-project/assets/154576898/e4e08003-70aa-41b8-8a57-eafdb0513f39)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
  - [x] Create a new `div` element with the `data-view` attribute that has an assigned value of `details`. This will go below the search results section in the html.
     - [x] Make sure this section is hidden and update the `viewSwap` function reflect the changes.
  - [x] Use HTML to create dummy page that will reflect the finished page.
     - [x] Make sure it is responsive and matches the wireframes
  - [x]  create a new function called `renderDetails` with one parameter `anime`. This parameter will represent the object within the data array. 
     - [x] This function should generate a DOM tree for the anime when the user clicks on the anchor element on the search results page.
  - [x] Update the `search` object and respective interface to have the property `animeId`. It's value will be a number that matches the id in that data array returned by the fetch. 
     - [x] Update the interface to also have the properties that will be displayed on the `derails` view. 
  - [x] In the `renderSearch` function update the `li` element to have a new attribute `data-id`. It's value will be the number in ID property created in the search object.
     - [x] add an event handler to the anchor element generated by the function, it should listen for click event.
     - [x] In the call back function the `viewSwap` function should be called with the argument `details`.
     - [x] When the anchor element is clicked the `data-id` should be retrieved and used to a fetch request.
     - [x] With the response from the API create a new object with all the properties that will be displayed on the `details` view. 
     - [x] pass the object through the `renderDetails` function as an argument. 
     - [x] append the `data-view` `div` element.
     - [x] At the top of the callback function update it to remove child elements of the `details` view `div`. This will make sure that only one anime's details are ever displayed even if the user decides search and view more anime. 

- **Clean Up**
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
